/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lms;

import java.awt.Color;
import java.sql.*;
import java.util.logging.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author Mohammed
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    Connection con;
    public Admin() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        con = MyConnection.createConnection();
        FillAddTableModel();
        FillTableModel();
        FillTeacherTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        allTable = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel11 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        teacherTable = new javax.swing.JTable();
        jPanel34 = new javax.swing.JPanel();
        newTeacherPanel = new javax.swing.JPanel();
        fNameT = new javax.swing.JTextField();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        lNameT = new javax.swing.JTextField();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        addTeacher = new javax.swing.JButton();
        femaleT = new javax.swing.JRadioButton();
        maleT = new javax.swing.JRadioButton();
        gender17 = new javax.swing.JLabel();
        passwordT = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        emailT = new javax.swing.JTextField();
        updateT = new javax.swing.JButton();
        deleteT = new javax.swing.JButton();
        adminCheckBoxT = new javax.swing.JCheckBox();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel8 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        newStudentPanel = new javax.swing.JPanel();
        fNameS = new javax.swing.JTextField();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        lNameS = new javax.swing.JTextField();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        addStudent = new javax.swing.JButton();
        femaleS = new javax.swing.JRadioButton();
        maleS = new javax.swing.JRadioButton();
        gender15 = new javax.swing.JLabel();
        passwordS = new javax.swing.JPasswordField();
        jLabel107 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emailS = new javax.swing.JTextField();
        updateS = new javax.swing.JButton();
        deleteS = new javax.swing.JButton();
        semesterS = new javax.swing.JTextField();
        adminS = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN");

        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel3.setBackground(new java.awt.Color(153, 51, 0));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Stencil", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.setBackground(new java.awt.Color(51, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));

        jScrollPane4.setBackground(new java.awt.Color(204, 204, 255));

        allTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Gender", "Teacher", "Admin"
            }
        ));
        allTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                allTableFocusGained(evt);
            }
        });
        allTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(allTable);

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/main/resources/com/group8/view/images/Back.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(150, 150, 150))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel9);

        jTabbedPane1.addTab("                              All                              ", jToolBar1);

        jToolBar2.setRollover(true);

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));

        jPanel33.setBackground(new java.awt.Color(204, 204, 255));

        teacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Email", "Gender"
            }
        ));
        teacherTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(teacherTable);

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 155, Short.MAX_VALUE))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        newTeacherPanel.setBackground(new java.awt.Color(102, 102, 102));
        newTeacherPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        jLabel108.setBackground(new java.awt.Color(102, 102, 102));
        jLabel108.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(255, 255, 255));
        jLabel108.setText("First Name: ");

        jLabel109.setBackground(new java.awt.Color(102, 102, 102));
        jLabel109.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(255, 255, 255));
        jLabel109.setText("Last Name: ");

        jLabel110.setBackground(new java.awt.Color(102, 102, 102));
        jLabel110.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(255, 255, 255));
        jLabel110.setText("Password:");

        jLabel111.setBackground(new java.awt.Color(102, 102, 102));
        jLabel111.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(255, 255, 255));
        jLabel111.setText("Email:");

        addTeacher.setText("Add Teacher");
        addTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherActionPerformed(evt);
            }
        });

        buttonGroup2.add(femaleT);
        femaleT.setForeground(new java.awt.Color(255, 153, 153));
        femaleT.setText("FEMALE");
        femaleT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleTActionPerformed(evt);
            }
        });

        buttonGroup2.add(maleT);
        maleT.setForeground(new java.awt.Color(0, 204, 204));
        maleT.setText("MALE");

        gender17.setBackground(new java.awt.Color(102, 102, 102));
        gender17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gender17.setForeground(new java.awt.Color(255, 255, 255));
        gender17.setText("Gender: ");

        passwordT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Add New Teacher");

        updateT.setText("Update");
        updateT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTActionPerformed(evt);
            }
        });

        deleteT.setText("Delete");
        deleteT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTActionPerformed(evt);
            }
        });

        adminCheckBoxT.setForeground(new java.awt.Color(255, 255, 255));
        adminCheckBoxT.setText("Admin");

        javax.swing.GroupLayout newTeacherPanelLayout = new javax.swing.GroupLayout(newTeacherPanel);
        newTeacherPanel.setLayout(newTeacherPanelLayout);
        newTeacherPanelLayout.setHorizontalGroup(
            newTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newTeacherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(newTeacherPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(newTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newTeacherPanelLayout.createSequentialGroup()
                        .addGroup(newTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel109)
                            .addComponent(jLabel110, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel108, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(newTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newTeacherPanelLayout.createSequentialGroup()
                                .addComponent(fNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(newTeacherPanelLayout.createSequentialGroup()
                                .addGroup(newTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(femaleT, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(newTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15))))
                    .addGroup(newTeacherPanelLayout.createSequentialGroup()
                        .addGroup(newTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newTeacherPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(maleT, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(adminCheckBoxT)
                            .addComponent(deleteT, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateT, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        newTeacherPanelLayout.setVerticalGroup(
            newTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newTeacherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel108)
                    .addComponent(fNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel109)
                    .addComponent(lNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel111)
                    .addComponent(emailT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel110)
                    .addComponent(passwordT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(gender17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleT)
                    .addComponent(femaleT))
                .addGap(29, 29, 29)
                .addComponent(adminCheckBoxT)
                .addGap(36, 36, 36)
                .addComponent(addTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newTeacherPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newTeacherPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 543, Short.MAX_VALUE))
                .addContainerGap())
        );

        jToolBar2.add(jPanel11);

        jTabbedPane1.addTab("                 Teacher                 ", jToolBar2);

        jToolBar3.setBackground(new java.awt.Color(204, 204, 255));
        jToolBar3.setRollover(true);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        newStudentPanel.setBackground(new java.awt.Color(102, 102, 102));
        newStudentPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        jLabel103.setBackground(new java.awt.Color(102, 102, 102));
        jLabel103.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(255, 255, 255));
        jLabel103.setText("First Name: ");

        jLabel104.setBackground(new java.awt.Color(102, 102, 102));
        jLabel104.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(255, 255, 255));
        jLabel104.setText("Last Name: ");

        jLabel105.setBackground(new java.awt.Color(102, 102, 102));
        jLabel105.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(255, 255, 255));
        jLabel105.setText("Password:");

        jLabel106.setBackground(new java.awt.Color(102, 102, 102));
        jLabel106.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(255, 255, 255));
        jLabel106.setText("Email:");

        addStudent.setText("Add Student");
        addStudent.setActionCommand("Add Teacher");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        buttonGroup1.add(femaleS);
        femaleS.setForeground(new java.awt.Color(255, 153, 153));
        femaleS.setText("FEMALE");
        femaleS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleSActionPerformed(evt);
            }
        });

        buttonGroup1.add(maleS);
        maleS.setForeground(new java.awt.Color(0, 204, 204));
        maleS.setText("MALE");

        gender15.setBackground(new java.awt.Color(102, 102, 102));
        gender15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gender15.setForeground(new java.awt.Color(255, 255, 255));
        gender15.setText("Gender: ");

        passwordS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordSKeyPressed(evt);
            }
        });

        jLabel107.setBackground(new java.awt.Color(102, 102, 102));
        jLabel107.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(255, 255, 255));
        jLabel107.setText("Semester:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Add New Student");

        updateS.setText("Update");
        updateS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSActionPerformed(evt);
            }
        });

        deleteS.setText("Delete");
        deleteS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSActionPerformed(evt);
            }
        });

        adminS.setForeground(new java.awt.Color(255, 255, 255));
        adminS.setText("Admin");

        javax.swing.GroupLayout newStudentPanelLayout = new javax.swing.GroupLayout(newStudentPanel);
        newStudentPanel.setLayout(newStudentPanelLayout);
        newStudentPanelLayout.setHorizontalGroup(
            newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(newStudentPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStudentPanelLayout.createSequentialGroup()
                        .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel104)
                                .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel106, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel103, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel107))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStudentPanelLayout.createSequentialGroup()
                                .addComponent(fNameS, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(newStudentPanelLayout.createSequentialGroup()
                                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNameS, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailS, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordS, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(semesterS, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))))
                    .addGroup(newStudentPanelLayout.createSequentialGroup()
                        .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminS)
                            .addComponent(deleteS, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateS, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(newStudentPanelLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(maleS, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(femaleS, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(addStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        newStudentPanelLayout.setVerticalGroup(
            newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel103)
                    .addComponent(fNameS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel104)
                    .addComponent(lNameS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel106)
                    .addComponent(emailS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel105)
                    .addComponent(passwordS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel107)
                    .addComponent(semesterS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(gender15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleS)
                    .addComponent(femaleS))
                .addGap(18, 18, 18)
                .addComponent(adminS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addComponent(newStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Semester", "Gender"
            }
        ));
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentTable);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                    .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jToolBar3.add(jPanel8);

        jTabbedPane1.addTab("                 Student                 ", jToolBar3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public boolean isEmptyS(){
        return fNameS.getText().equals("") || lNameS.getText().equals("") ||
               emailS.getText().equals("") || passwordS.getText().equals("") ||
                semesterS.getText().equals("") || (!femaleS.isSelected() && !maleS.isSelected());
    }
    
    public boolean isEmptyT(){
        return fNameT.getText().equals("") || lNameT.getText().equals("") ||
               emailT.getText().equals("") || passwordT.getText().equals("") ||
               (!femaleT.isSelected() && !maleT.isSelected());
    }
    
    public void FillTableModel(){
        try{
            DefaultTableModel tb = (DefaultTableModel)studentTable.getModel();
            tb.setRowCount(0);
            Statement smt = con.createStatement();
            ResultSet rs = smt.executeQuery("select id, name, email, semester, gender from student");
            while(rs.next()){
                String id = rs.getString("id");
                String name = rs.getString("name");
                String email = rs.getString("email");
                String semester = rs.getString("semester");
                String gender = rs.getString("gender");
                String tbData[] = {id, name, email, semester, gender};
                tb.addRow(tbData);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Failed!");
        }
    }
    
    public void FillTeacherTableModel(){
        try{
            DefaultTableModel tb = (DefaultTableModel)teacherTable.getModel();
            tb.setRowCount(0);
            Statement smt = con.createStatement();
            ResultSet rs = smt.executeQuery("select name, email, gender from teacher");
            while(rs.next()){
                String name = rs.getString("name");
                String email = rs.getString("email");
                String gender = rs.getString("gender");
                String tbData[] = {name, email, gender};
                tb.addRow(tbData);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Failed!");
        }
    }
   
    
    public void FillAddTableModel(){
        try{
            DefaultTableModel tb = (DefaultTableModel)allTable.getModel();
            tb.setRowCount(0);
            Statement smt = con.createStatement();
            ResultSet rs = smt.executeQuery("select name, email, gender, teacher, admin from users");
            while(rs.next()){
                String name = rs.getString("name");
                String email = rs.getString("email");
                String teacher = rs.getString("teacher");
                String gender = rs.getString("gender");
                String admin = rs.getString("admin");
                String tbData[] = {name, email, gender, teacher, admin};
                tb.addRow(tbData);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Failed!");
        }
    }
    
    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        // TODO add your handling code here:
        if(isEmptyS()){
            JOptionPane.showMessageDialog(this,"All fields are required");
        }
        try{
            Student s;
            boolean admin = adminS.isSelected();
            Statement smt = con.createStatement();
            if(maleS.isSelected()){
                s = new Student(fNameS.getText() + " " + lNameS.getText(), emailS.getText(), passwordS.getText(), "male", Integer.parseInt(semesterS.getText()));
            }
            else{
                s = new Student(fNameS.getText() + " " + lNameS.getText(), emailS.getText(), passwordS.getText(), "female", Integer.parseInt(semesterS.getText()));
            }
        
            smt.executeUpdate("insert into student(name, email, password, semester, gender) values('" + s.getName() + "', '" + s.getEmail() + "', '" + s.getPassword() + "', " + s.getSemester() + ", '" + s.getGender() + "')");
            smt.executeUpdate("insert into users(name, email, password, gender, teacher, admin) values('" + s.getName() + "', '" + s.getEmail() + "', '" + s.getPassword() + "', '" + s.getGender() + "' , 0, " + s.isAdmin() + ")");
            smt.close();
        }
        catch(SQLException e){
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
        FillTableModel();
    }//GEN-LAST:event_addStudentActionPerformed

    private void femaleSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleSActionPerformed

    private void passwordSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordSKeyPressed
        // TODO add your handling code here:
        passwordS.setEchoChar('*');
        Color color=new Color(0,0,0);
        passwordS.setForeground(color);
    }//GEN-LAST:event_passwordSKeyPressed

    private void deleteSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSActionPerformed
        // TODO add your handling code here:
        try{
            Statement smt = con.createStatement();
            String email = emailS.getText();
            smt.executeUpdate("delete from student where email = '" + email + "'");
            smt.executeUpdate("delete from users where email = '" + email + "'");
            FillTableModel();
            smt.close();
        }
        catch(SQLException e){
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_deleteSActionPerformed

    private void updateSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSActionPerformed
        // TODO add your handling code here:
        try{
            boolean admin = adminS.isSelected();
            Student s;
            PreparedStatement smt = con.prepareStatement("update student set name = ?, email = ?, password = ?, gender = ?, semester = ? where email = '" + (String) studentTable.getValueAt(studentTable.getSelectedRow(),2) + "'");
            if(maleS.isSelected()){
                s = new Student(fNameS.getText() + " " + lNameS.getText(), emailS.getText(), passwordS.getText(), "male", Integer.parseInt(semesterS.getText()));
            }
            else{
                s = new Student(fNameS.getText() + " " + lNameS.getText(), emailS.getText(), passwordS.getText(), "female", Integer.parseInt(semesterS.getText()));
            }
            smt.setString(1, s.getName());
            smt.setString(2, s.getEmail());
            smt.setString(3, s.getPassword());
            smt.setString(4, s.getGender());
            smt.setInt(5, s.getSemester());
            smt.executeUpdate();
            
            Statement smt2 = con.createStatement();
            smt2.executeUpdate("update users set email = '" + emailS.getText() + "', password = '" + passwordS.getText() + "', admin = " + admin + " where email = '" + (String) studentTable.getValueAt(studentTable.getSelectedRow(),2) + "'");
            FillTableModel();
            smt.close();
            smt2.close();
        }
        catch(SQLException e){
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_updateSActionPerformed

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        // TODO add your handling code here:
        try{
            Statement smt = con.createStatement();
            ResultSet rs = smt.executeQuery("select password from student where email = '" + (String) studentTable.getValueAt(studentTable.getSelectedRow(),2) + "'");
            String name = (String) studentTable.getValueAt(studentTable.getSelectedRow(),1);
            String[] fName = name.split(" ");
            fNameS.setText(fName[0]);
            lNameS.setText(fName[1]);
            emailS.setText((String) studentTable.getValueAt(studentTable.getSelectedRow(),2));
            semesterS.setText((String) studentTable.getValueAt(studentTable.getSelectedRow(),3));
            String gender = (String) studentTable.getValueAt(studentTable.getSelectedRow(),4);
            if(gender.equals("female"))
                femaleS.setSelected(true);
            else{
                maleS.setSelected(true);
            }
            if(rs.next()){
                passwordS.setText(rs.getString("password"));
            }
            Statement smt2 = con.createStatement();
            ResultSet rs2 = smt2.executeQuery("select admin from users where email = '" + (String) studentTable.getValueAt(studentTable.getSelectedRow(),2) + "'");
            if(rs2.next()){
                if(rs2.getInt("admin") == 1)
                    adminS.setSelected(true);
                else
                    adminS.setSelected(false);
            }
        }
        catch(SQLException e){
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_studentTableMouseClicked

    private void deleteTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTActionPerformed
        // TODO add your handling code here:
        try{
            Statement smt = con.createStatement();
            String email = emailT.getText();
            smt.executeUpdate("delete from teacher where email = '" + email + "'");
            smt.executeUpdate("delete from users where email = '" + email + "'");
            FillTeacherTableModel();
            smt.close();
        }
        catch(SQLException e){
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_deleteTActionPerformed

    private void updateTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTActionPerformed
        // TODO add your handling code here:
        try{
            Teacher t;
            boolean admin = adminCheckBoxT.isSelected();
            PreparedStatement smt = con.prepareStatement("update teacher set name = ?, email = ?, password = ?, gender = ? where email = '" + (String) teacherTable.getValueAt(teacherTable.getSelectedRow(),1) + "'");
            if(maleT.isSelected()){
                t = new Teacher(fNameT.getText() + " " + lNameT.getText(), emailT.getText(), passwordS.getText(), "male");
            }
            else{
                t = new Teacher(fNameT.getText() + " " + lNameT.getText(), emailT.getText(), passwordS.getText(), "female");
            }
            smt.setString(1, t.getName());
            smt.setString(2, t.getEmail());
            smt.setString(3, t.getPassword());
            smt.setString(4, t.getGender());
            smt.executeUpdate();

            Statement smt2 = con.createStatement();
            smt2.executeUpdate("update users set email = '" + emailT.getText() + "', password = '" + passwordT.getText() + "', admin = " + admin + " where email = '" + (String) teacherTable.getValueAt(teacherTable.getSelectedRow(),1) + "'");
            FillTeacherTableModel();
            smt.close();
            smt2.close();
        }
        catch(SQLException e){
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_updateTActionPerformed

    private void passwordTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTKeyPressed

    private void femaleTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleTActionPerformed

    private void addTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherActionPerformed
        // TODO add your handling code here:
        if(isEmptyT()){
            JOptionPane.showMessageDialog(this,"All fields are required");
        }
        try{
            Teacher t;
            boolean admin = adminCheckBoxT.isSelected();
            Statement smt = con.createStatement();
            if(maleT.isSelected()){
                t = new Teacher(fNameT.getText() + " " + lNameT.getText(), emailT.getText(), passwordT.getText(), "male");
            }
            else{
                t = new Teacher(fNameT.getText() + " " + lNameT.getText(), emailT.getText(), passwordT.getText(), "female");
            }

            smt.executeUpdate("insert into teacher(name, email, password, gender) values('" + t.getName() + "', '" + t.getEmail() + "', '" + t.getPassword() + "', '" + t.getGender() + "')");
            smt.executeUpdate("insert into users(name, email, password, gender, teacher, admin) values('" + t.getName() + "', '" + t.getEmail() + "', '" + t.getPassword() + "', '" + t.getGender() + "' , 1, " + admin + ")");
            smt.close();
        }
        catch(SQLException e){
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
        FillTeacherTableModel();
    }//GEN-LAST:event_addTeacherActionPerformed

    private void allTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allTableMouseClicked
        // TODO add your handling code here:
        FillAddTableModel();
    }//GEN-LAST:event_allTableMouseClicked

    private void teacherTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherTableMouseClicked
        // TODO add your handling code here:
         try{
            Statement smt = con.createStatement();
            ResultSet rs = smt.executeQuery("select password from teacher where email = '" + (String) teacherTable.getValueAt(teacherTable.getSelectedRow(),1) + "'");
            String name = (String) teacherTable.getValueAt(teacherTable.getSelectedRow(),0);
            String[] fName = name.split(" ");
            fNameT.setText(fName[0]);
            lNameT.setText(fName[1]);
            emailT.setText((String) teacherTable.getValueAt(teacherTable.getSelectedRow(),1));
            String gender = (String) teacherTable.getValueAt(teacherTable.getSelectedRow(),2);
            if(gender.equals("female"))
                femaleT.setSelected(true);
            else{
                maleT.setSelected(true);
            }
            if(rs.next()){
                passwordT.setText(rs.getString("password"));
            }
            Statement smt2 = con.createStatement();
            ResultSet rs2 = smt2.executeQuery("select admin from users where email = '" + (String) teacherTable.getValueAt(teacherTable.getSelectedRow(),1) + "'");
            if(rs2.next()){
                if(rs2.getInt("admin") == 1)
                    adminCheckBoxT.setSelected(true);
                else
                    adminCheckBoxT.setSelected(false);
            }
        }
        catch(SQLException e){
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_teacherTableMouseClicked

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
        FillAddTableModel();
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void allTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_allTableFocusGained
        // TODO add your handling code here:
        FillAddTableModel();
    }//GEN-LAST:event_allTableFocusGained

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new SignIn().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton addStudent;
    private javax.swing.JButton addTeacher;
    private javax.swing.JCheckBox adminCheckBoxT;
    private javax.swing.JCheckBox adminS;
    private javax.swing.JTable allTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton deleteS;
    private javax.swing.JButton deleteT;
    private javax.swing.JTextField emailS;
    private javax.swing.JTextField emailT;
    private javax.swing.JTextField fNameS;
    private javax.swing.JTextField fNameT;
    private javax.swing.JRadioButton femaleS;
    private javax.swing.JRadioButton femaleT;
    private javax.swing.JLabel gender15;
    private javax.swing.JLabel gender17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JTextField lNameS;
    private javax.swing.JTextField lNameT;
    private javax.swing.JRadioButton maleS;
    private javax.swing.JRadioButton maleT;
    private javax.swing.JPanel newStudentPanel;
    private javax.swing.JPanel newTeacherPanel;
    private javax.swing.JPasswordField passwordS;
    private javax.swing.JPasswordField passwordT;
    private javax.swing.JTextField semesterS;
    private javax.swing.JTable studentTable;
    private javax.swing.JTable teacherTable;
    private javax.swing.JButton updateS;
    private javax.swing.JButton updateT;
    // End of variables declaration//GEN-END:variables
}
