/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lms;
import java.sql.*;
import java.util.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author A M A
 */
public class DeleteQuestion extends javax.swing.JFrame {

    /**
     * Creates new form DeleteQuestion
     */
    public DeleteQuestion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CloseButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CNameText = new javax.swing.JTextField();
        QidText = new javax.swing.JTextField();
        QText = new javax.swing.JTextField();
        Opt1Text = new javax.swing.JTextField();
        Opt2Text = new javax.swing.JTextField();
        Opt3Text = new javax.swing.JTextField();
        Opt4Text = new javax.swing.JTextField();
        AnswerText = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(150, 183));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        CNameLabel.setText("Course Name : ");
        getContentPane().add(CNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Adventure", 1, 40)); // NOI18N
        jLabel2.setText("Delete Question");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 6, 296, -1));

        CloseButton.setBackground(new java.awt.Color(255, 255, 255));
        CloseButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CloseButton.setForeground(new java.awt.Color(255, 51, 51));
        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Close.png"))); // NOI18N
        CloseButton.setText("Close");
        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 1066, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Question ID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Question :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Option 1 :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Option 2 :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("Option 3 :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("Option 4 :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setText("Answer :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        CNameText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(CNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 700, -1));

        QidText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(QidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 260, -1));

        QText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(QText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 700, -1));

        Opt1Text.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(Opt1Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 700, -1));

        Opt2Text.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(Opt2Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 700, -1));

        Opt3Text.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(Opt3Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 700, -1));

        Opt4Text.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(Opt4Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 700, -1));

        AnswerText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(AnswerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 700, -1));

        SearchButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/search.png"))); // NOI18N
        SearchButton.setText("Search");
        SearchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        DeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/save.png"))); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        ClearButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/clear.png"))); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
         QuestionManagement.open=0;
         setVisible(false);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String id = QidText.getText();
         try
        {
           Connection con = MyConnection.createConnection();
           Statement st = con.createStatement();
           ResultSet rs =st.executeQuery(" select * from question where id ="+id);
           if(rs.next())
           {
              QText.setText(rs.getString(2));
              Opt1Text.setText(rs.getString(3));
              Opt2Text.setText(rs.getString(4));
              Opt3Text.setText(rs.getString(5));
              Opt4Text.setText(rs.getString(6));
              AnswerText.setText(rs.getString(7));
              CNameText.setText(rs.getString(8));
              QidText.setEditable(false);
           }
           else
           {
            JFrame jf = new JFrame();            
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , "Question ID does not exist");
           }
        }
        catch (Exception e)
        {
            JFrame jf = new JFrame();            
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , e);
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        String id = QidText.getText();
       try
        {
           Connection con = MyConnection.createConnection();
           PreparedStatement pa = con.prepareStatement("delete from question where id=? ");            
           pa.setString(1, id); 
           pa.executeUpdate();
           JFrame jf = new JFrame();
           jf.setAlwaysOnTop(true);
           JOptionPane.showMessageDialog(jf , "successfully Deleted");
           setVisible(false);
           new DeleteQuestion().setVisible(true);                    
        }
        catch (Exception e)
        {
            JFrame jf = new JFrame();           
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , e);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
         QidText.setEditable(true);
         QidText.setText("");
         QText.setText("");
         Opt1Text.setText("");
         Opt2Text.setText("");
         Opt3Text.setText("");
         Opt4Text.setText("");
         AnswerText.setText("");
         CNameText.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnswerText;
    private javax.swing.JLabel CNameLabel;
    private javax.swing.JTextField CNameText;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField Opt1Text;
    private javax.swing.JTextField Opt2Text;
    private javax.swing.JTextField Opt3Text;
    private javax.swing.JTextField Opt4Text;
    private javax.swing.JTextField QText;
    private javax.swing.JTextField QidText;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
