
package lms;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author A M A
 */
public class ExamManagement extends javax.swing.JFrame {
     public static int open = 0 ;
    /**
     * Creates new form ExamManagement
     */
    public ExamManagement() {
        initComponents();
         this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        AddNewExamMenu = new javax.swing.JMenu();
        EmptyMenu5 = new javax.swing.JMenu();
        UpdateExamMenu = new javax.swing.JMenu();
        EmptyMenu4 = new javax.swing.JMenu();
        DeleteExamMenu = new javax.swing.JMenu();
        EmptyMenu3 = new javax.swing.JMenu();
        AllExamsMenu = new javax.swing.JMenu();
        EmptyMenu2 = new javax.swing.JMenu();
        LogoutMenu = new javax.swing.JMenu();
        EmptyMenu1 = new javax.swing.JMenu();
        CloseMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Back.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 600, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/correctingExams.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(137, 197, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exam Management", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(0, 102, 153))); // NOI18N
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        AddNewExamMenu.setBackground(new java.awt.Color(51, 153, 255));
        AddNewExamMenu.setForeground(new java.awt.Color(0, 0, 0));
        AddNewExamMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/addExam.png"))); // NOI18N
        AddNewExamMenu.setText("Add New Exam");
        AddNewExamMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddNewExamMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddNewExamMenu.setInheritsPopupMenu(true);
        AddNewExamMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewExamMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(AddNewExamMenu);

        EmptyMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EmptyMenu5.setEnabled(false);
        EmptyMenu5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmptyMenu5.setMaximumSize(new java.awt.Dimension(75, 32767));
        jMenuBar1.add(EmptyMenu5);

        UpdateExamMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/UpdateExam.png"))); // NOI18N
        UpdateExamMenu.setText("Update Exam");
        UpdateExamMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateExamMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateExamMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateExamMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(UpdateExamMenu);

        EmptyMenu4.setEnabled(false);
        EmptyMenu4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmptyMenu4.setMaximumSize(new java.awt.Dimension(75, 32767));
        jMenuBar1.add(EmptyMenu4);

        DeleteExamMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/DeleteExam.png"))); // NOI18N
        DeleteExamMenu.setText("Delete Exam");
        DeleteExamMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteExamMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteExamMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteExamMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(DeleteExamMenu);

        EmptyMenu3.setEnabled(false);
        EmptyMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmptyMenu3.setMaximumSize(new java.awt.Dimension(85, 32767));
        jMenuBar1.add(EmptyMenu3);

        AllExamsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/AllExams.png"))); // NOI18N
        AllExamsMenu.setText("All Exams");
        AllExamsMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AllExamsMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AllExamsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllExamsMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(AllExamsMenu);

        EmptyMenu2.setEnabled(false);
        EmptyMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmptyMenu2.setMaximumSize(new java.awt.Dimension(85, 32767));
        jMenuBar1.add(EmptyMenu2);

        LogoutMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Logout.png"))); // NOI18N
        LogoutMenu.setText("Logout");
        LogoutMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMenuMouseClicked(evt);
            }
        });
        LogoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(LogoutMenu);

        EmptyMenu1.setEnabled(false);
        EmptyMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmptyMenu1.setMaximumSize(new java.awt.Dimension(85, 32767));
        jMenuBar1.add(EmptyMenu1);

        CloseMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Close.png"))); // NOI18N
        CloseMenu.setText("Exit");
        CloseMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CloseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMenuMouseClicked(evt);
            }
        });
        CloseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(CloseMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CloseMenuActionPerformed

    private void CloseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMenuMouseClicked
        // TODO add your handling code here:
         JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(jf,"do u realy want to exit app ","select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_CloseMenuMouseClicked

    private void LogoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMenuMouseClicked
        // TODO add your handling code here:
          JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(jf,"do u realy want to log out","select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new SignIn().setVisible(true);
        }
    }//GEN-LAST:event_LogoutMenuMouseClicked

    private void AddNewExamMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewExamMenuMouseClicked
        // TODO add your handling code here:
        if(open==0) 
        {
            new AddNewExam().setVisible(true);
            open = 1 ; 
        }
        else
        {
            JFrame jf = new JFrame();           
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , "one form is allready open ");
        }
    }//GEN-LAST:event_AddNewExamMenuMouseClicked

    private void UpdateExamMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateExamMenuMouseClicked
        // TODO add your handling code here:
         if(open==0) 
        {
            new UpdateExam().setVisible(true);
            open = 1 ; 
        }
        else
        {
            JFrame jf = new JFrame();           
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , "one form is allready open ");
        }
    }//GEN-LAST:event_UpdateExamMenuMouseClicked

    private void DeleteExamMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteExamMenuMouseClicked
        // TODO add your handling code here:
        if(open==0) 
        {
            new DeleteExam().setVisible(true);
            open = 1 ; 
        }
        else
        {
            JFrame jf = new JFrame();           
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , "one form is allready open ");
        }
    }//GEN-LAST:event_DeleteExamMenuMouseClicked

    private void AllExamsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllExamsMenuMouseClicked
        // TODO add your handling code here:
          if(open==0) 
        {
            new AllExams().setVisible(true);
            open = 1 ; 
        }
        else
        {
            JFrame jf = new JFrame();           
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , "one form is allready open ");
        }
    }//GEN-LAST:event_AllExamsMenuMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new TeacherHomepage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LogoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LogoutMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AddNewExamMenu;
    private javax.swing.JMenu AllExamsMenu;
    private javax.swing.JMenu CloseMenu;
    private javax.swing.JMenu DeleteExamMenu;
    private javax.swing.JMenu EmptyMenu1;
    private javax.swing.JMenu EmptyMenu2;
    private javax.swing.JMenu EmptyMenu3;
    private javax.swing.JMenu EmptyMenu4;
    private javax.swing.JMenu EmptyMenu5;
    private javax.swing.JMenu LogoutMenu;
    private javax.swing.JMenu UpdateExamMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
