package lms;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aisha ali
 */
public class LogicDesignExam extends javax.swing.JFrame {
    
    String [] questions = {"1 + 1 = ?","3 - 3 = ?","5 + 5 = ?","10 × 9 =?","100 - 50 = ?"};
    // the last item is the correct answer
    String options [] [] ={{"10","4","2","6","2"},{"7","2","5","0","0"},{"10","8","5","6","10"},{"90","16","5","1","90"},{"100","44","50","20","50"}};
    int index = 0, correct = 0; 
    
    ButtonGroup bg = new ButtonGroup();

    /**
     * Creates new form Exam1
     */
    public LogicDesignExam() {
        initComponents();
        this.setLocationRelativeTo(null);      
        // didn't create same choise in the next quest
        bg.add(Opt2Button);
        bg.add(Opt1Button);
        bg.add(Opt4Button);
        bg.add(Opt3Button);
        
        jButton_Next_QActionPerformed(null);
    }
    
     public void getSelectedOption (JRadioButton rbtn )
    {
        // get the selected value from the radiobutton
        // increment the index 
        // disaple the radiobutton
        // check if the user selected the right answer
        System.out.println(rbtn.getText());
        System.out.println(options[index][4]);
        if (rbtn.getText().equals(options[index][4]))
        {
            correct++;
        }
        
        // to go to the next question
        index++;
        enableRbuttons(false);
    }
    
    //enable / disable radiobutton
    public void enableRbuttons(boolean yes_or_no)
    {
        Opt2Button.setEnabled(yes_or_no);
        Opt1Button.setEnabled(yes_or_no);
        Opt4Button.setEnabled(yes_or_no);
        Opt3Button.setEnabled(yes_or_no);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Opt2Button = new javax.swing.JRadioButton();
        Opt4Button = new javax.swing.JRadioButton();
        Opt3Button = new javax.swing.JRadioButton();
        Opt1Button = new javax.swing.JRadioButton();
        jButton_Next_Q = new javax.swing.JButton();
        jPanel_Q_Counter = new javax.swing.JPanel();
        Lbl_Question = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(150, 183));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Opt2Button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Opt2Button.setText("jRadioButton1");
        Opt2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt2ButtonActionPerformed(evt);
            }
        });

        Opt4Button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Opt4Button.setText("jRadioButton1");
        Opt4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt4ButtonActionPerformed(evt);
            }
        });

        Opt3Button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Opt3Button.setText("jRadioButton1");
        Opt3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt3ButtonActionPerformed(evt);
            }
        });

        Opt1Button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Opt1Button.setText("jRadioButton1");
        Opt1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt1ButtonActionPerformed(evt);
            }
        });

        jButton_Next_Q.setBackground(new java.awt.Color(255, 51, 51));
        jButton_Next_Q.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Next_Q.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Next_Q.setText("Next");
        jButton_Next_Q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_Next_QMousePressed(evt);
            }
        });
        jButton_Next_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Next_QActionPerformed(evt);
            }
        });

        jPanel_Q_Counter.setBackground(new java.awt.Color(204, 204, 204));

        Lbl_Question.setBackground(new java.awt.Color(204, 204, 204));
        Lbl_Question.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lbl_Question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Question.setText("Questions Here");

        javax.swing.GroupLayout jPanel_Q_CounterLayout = new javax.swing.GroupLayout(jPanel_Q_Counter);
        jPanel_Q_Counter.setLayout(jPanel_Q_CounterLayout);
        jPanel_Q_CounterLayout.setHorizontalGroup(
            jPanel_Q_CounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Q_CounterLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Lbl_Question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );
        jPanel_Q_CounterLayout.setVerticalGroup(
            jPanel_Q_CounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Q_CounterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbl_Question, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(331, Short.MAX_VALUE)
                .addComponent(jButton_Next_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Opt4Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Q_Counter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Opt2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Opt1Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Opt3Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Q_Counter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Opt1Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Opt2Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Opt3Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Opt4Button)
                .addGap(186, 186, 186)
                .addComponent(jButton_Next_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Opt2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt2ButtonActionPerformed
        // TODO add your handling code here:
        getSelectedOption(Opt2Button);
    }//GEN-LAST:event_Opt2ButtonActionPerformed

    private void Opt4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt4ButtonActionPerformed
        // TODO add your handling code here:
        getSelectedOption(Opt4Button);
    }//GEN-LAST:event_Opt4ButtonActionPerformed

    private void Opt3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt3ButtonActionPerformed
        // TODO add your handling code here:
        getSelectedOption(Opt3Button);
    }//GEN-LAST:event_Opt3ButtonActionPerformed

    private void jButton_Next_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Next_QActionPerformed

        if (jButton_Next_Q.getText ().equals("Restart The Quiz") )
        {
            //restart the quiz
            index = 0;
            correct = 0;
        }

        if (index == questions.length)
        {
            // display the user score
            Lbl_Question.setText("Your Score is :" +correct+ "/" +questions.length);
            jButton_Next_Q.setText("Close");     
        }
       
        else {
            // enable radio buttons
            enableRbuttons(true);            
            // display the next question:
   
            Lbl_Question.setText(questions [index]);
            Opt2Button.setText(options [index][0]);
            Opt1Button.setText(options [index][1]);
            Opt4Button.setText(options [index][2]);
            Opt3Button.setText(options [index][3]);

            if (index == questions.length-1){
                jButton_Next_Q.setText("Finish and See the Result");
            }                
        }

        // clear the selection
        bg.clearSelection();

    }//GEN-LAST:event_jButton_Next_QActionPerformed

    private void Opt1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt1ButtonActionPerformed
        // TODO add your handling code here:
        getSelectedOption(Opt1Button);
    }//GEN-LAST:event_Opt1ButtonActionPerformed

    private void jButton_Next_QMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Next_QMousePressed
        // TODO add your handling code here:
        if(  jButton_Next_Q.getText()=="Close")
        {
            // display the user score
            RegisteredCourses.open=0;
            setVisible(false);           
        }
    }//GEN-LAST:event_jButton_Next_QMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogicDesignExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogicDesignExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogicDesignExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogicDesignExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogicDesignExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Question;
    private javax.swing.JRadioButton Opt1Button;
    private javax.swing.JRadioButton Opt2Button;
    private javax.swing.JRadioButton Opt3Button;
    private javax.swing.JRadioButton Opt4Button;
    private javax.swing.JButton jButton_Next_Q;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Q_Counter;
    // End of variables declaration//GEN-END:variables
}
