/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lms;

import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author Mohamed 
 */
public class Precentage extends javax.swing.JFrame {

    /**
     * Creates new form Precentage
     */
    double ctrPassPl = 0;
    double ctrAllPl = 0;
    double ctrApPl = 0;
    double ctrPassDS = 0;
    double ctrAllDS = 0;
    double ctrApDS =0 ;
    double ctrPassLOGIC =0 ;
    double ctrAllLOGIC =0 ;
    double ctrApLOGIC =0 ;
    double ctrPassMaths=0 ;
    double ctrApMaths=0 ;
    double ctrAllMaths=0 ;

    int Pl, Ds, Maths, Logic;
    
    Connection con ;
    public Precentage() {
        initComponents();
        this.setLocationRelativeTo(null);
        con =  MyConnection.createConnection();
        Fill();
    }
    
    public void Fill(){
        DecimalFormat decimalFormat = new DecimalFormat("0.0");
        try{
            Statement smt = con.createStatement();
            ResultSet rs = smt.executeQuery("select pl, ds, maths, logic from student");
            while(rs.next()){
                String pl = rs.getString("pl");
                if(rs.wasNull())
                    Pl = 0;
                else {
                    Pl = Integer.parseInt(pl);
                    ctrAllPl++;
                }

                String ds = rs.getString("ds");
                if(rs.wasNull())
                Ds = 0;
                else {
                    Ds = Integer.parseInt(ds);
                    ctrAllDS++;
                }

                String logic = rs.getString("logic");
                if(rs.wasNull())
                Logic = 0;
                else {
                    Logic = Integer.parseInt(logic);
                    ctrAllLOGIC++;
                }

                String maths = rs.getString("maths");
                if(rs.wasNull())
                Maths = 0;
                else {
                    Maths = Integer.parseInt(maths);
                    ctrAllMaths++;
                }

                //PL
                if(Pl >= 3){
                    ctrPassPl++;
                    if(Pl >= 4)
                    ctrApPl++;
                }

                //DS
                if(Ds >= 3){
                    ctrPassDS++;
                    if(Ds >= 4)
                    ctrApDS++;
                }

                //logic
                if(Logic >= 3){
                    ctrPassLOGIC++;
                    if(Logic >= 4)
                    ctrApLOGIC++;
                }

                //maths
                if(Maths >= 3){
                    ctrPassMaths++;
                    if(Maths >= 4)
                    ctrApMaths++;
                }
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Failed!");
        }
        double passPerPl = (ctrPassPl / ctrAllPl) * 100;
        double apPerPl = (ctrApPl / ctrAllPl) * 100;

        plPass.setText(decimalFormat.format(passPerPl) + "");
        plPassAp.setText(decimalFormat.format(apPerPl) + "");

        double passPerds = (ctrPassDS / ctrAllDS) * 100;
        double apPerds = (ctrApDS / ctrAllDS) * 100;

        dsPass.setText(decimalFormat.format(passPerds) + "");
        dsPassAp.setText(decimalFormat.format(apPerds) + "");

        double passPerLOGIC = (ctrPassLOGIC / ctrAllLOGIC) * 100;
        double apPerLOGIC = (ctrApLOGIC / ctrAllLOGIC) * 100;

        logicPass.setText(decimalFormat.format(passPerLOGIC) + "");
        logicPassAp.setText(decimalFormat.format(apPerLOGIC) + "");

        double passPerMaths = (ctrPassMaths / ctrAllMaths) * 100;
        double apPerMaths = (ctrApMaths / ctrAllMaths) * 100;
      
        mathsPass.setText(decimalFormat.format(passPerMaths) + "");
        mathsPassAp.setText(decimalFormat.format(apPerMaths) + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        plPassAp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dsPass = new javax.swing.JTextField();
        logicPass = new javax.swing.JTextField();
        mathsPass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        logicPassAp = new javax.swing.JTextField();
        dsPassAp = new javax.swing.JTextField();
        mathsPassAp = new javax.swing.JTextField();
        plPass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Statistics Page");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PL");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("DS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Logic");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Maths");

        plPassAp.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("pass percentage");

        dsPass.setEditable(false);

        logicPass.setEditable(false);
        logicPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicPassActionPerformed(evt);
            }
        });

        mathsPass.setEditable(false);
        mathsPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathsPassActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("A+ percentage");

        logicPassAp.setEditable(false);

        dsPassAp.setEditable(false);
        dsPassAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsPassApActionPerformed(evt);
            }
        });

        mathsPassAp.setEditable(false);

        plPass.setEditable(false);
        plPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logicPass, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dsPass, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mathsPass, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(mathsPassAp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addComponent(logicPassAp, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dsPassAp, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(plPassAp, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(199, 199, 199)
                    .addComponent(plPass, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(405, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plPassAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dsPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dsPassAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logicPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logicPassAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mathsPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mathsPassAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(plPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(379, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logicPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logicPassActionPerformed

    private void mathsPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathsPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mathsPassActionPerformed

    private void dsPassApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsPassApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsPassApActionPerformed

    private void plPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Precentage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Precentage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Precentage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Precentage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Precentage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dsPass;
    private javax.swing.JTextField dsPassAp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField logicPass;
    private javax.swing.JTextField logicPassAp;
    private javax.swing.JTextField mathsPass;
    private javax.swing.JTextField mathsPassAp;
    private javax.swing.JTextField plPass;
    private javax.swing.JTextField plPassAp;
    // End of variables declaration//GEN-END:variables
}
