package lms;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author A M A
 */
public class RegisteredCourses extends javax.swing.JFrame {

    /**
     * Creates new form RegisteredCourses
     */
    public static int open = 0 ;
    public RegisteredCourses() {
        initComponents();
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        RCourse2Text = new javax.swing.JTextField();
        RCourse1Text = new javax.swing.JTextField();
        RCourse3Text = new javax.swing.JTextField();
        RCourse4Text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LDExamButton = new javax.swing.JButton();
        PL2ExamButton = new javax.swing.JButton();
        DSExamButton = new javax.swing.JButton();
        ORExamButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(150, 183));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Adventure", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RegisteredCourses");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 450, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 14, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 112, 1360, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Your Registered Courses is :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 187, -1, -1));

        RCourse2Text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(RCourse2Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 184, 208, -1));

        RCourse1Text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(RCourse1Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 184, 206, -1));

        RCourse3Text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(RCourse3Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 184, 213, -1));

        RCourse4Text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(RCourse4Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1116, 184, 200, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Start The :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 326, -1, -1));

        LDExamButton.setBackground(new java.awt.Color(255, 153, 153));
        LDExamButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LDExamButton.setText("Logic Desgin Exam");
        LDExamButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LDExamButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LDExamButtonMouseClicked(evt);
            }
        });
        LDExamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LDExamButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LDExamButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 323, -1, -1));

        PL2ExamButton.setBackground(new java.awt.Color(153, 255, 153));
        PL2ExamButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PL2ExamButton.setText("PL2 Exam");
        PL2ExamButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PL2ExamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PL2ExamButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PL2ExamButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 323, -1, -1));

        DSExamButton.setBackground(new java.awt.Color(153, 153, 255));
        DSExamButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DSExamButton.setText("DS Exam");
        DSExamButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(DSExamButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(969, 323, -1, -1));

        ORExamButton.setBackground(new java.awt.Color(51, 255, 204));
        ORExamButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ORExamButton.setText("OR Exam");
        ORExamButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(ORExamButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1184, 323, -1, -1));

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/main/resources/com/group8/view/images/Back.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 660, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/main/resources/com/group8/view/images/CoursePageBackground_1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1890, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Homepage().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void LDExamButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LDExamButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LDExamButtonMouseClicked

    private void LDExamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LDExamButtonActionPerformed
        // TODO add your handling code here:
       if(open==0) 
        {
            new LogicDesignExam().setVisible(true);
            open = 1;
        }
        else
        {
            JFrame jf = new JFrame();           
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , "one form is already open ");
        }
    }//GEN-LAST:event_LDExamButtonActionPerformed

    private void PL2ExamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PL2ExamButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PL2ExamButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisteredCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisteredCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisteredCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisteredCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisteredCourses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DSExamButton;
    private javax.swing.JButton LDExamButton;
    private javax.swing.JButton ORExamButton;
    private javax.swing.JButton PL2ExamButton;
    private javax.swing.JTextField RCourse1Text;
    private javax.swing.JTextField RCourse2Text;
    private javax.swing.JTextField RCourse3Text;
    private javax.swing.JTextField RCourse4Text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
