package lms;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author A M A
 */
public class TeacherHomepage extends javax.swing.JFrame {
public static int open = 0 ;
    /**
     * Creates new form TeacherHomepage
     */
    public TeacherHomepage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EMButton = new javax.swing.JButton();
        QMButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EMButton.setBackground(new java.awt.Color(102, 204, 255));
        EMButton.setFont(new java.awt.Font("Adventure", 1, 36)); // NOI18N
        EMButton.setForeground(new java.awt.Color(0, 0, 0));
        EMButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/addExam.png"))); // NOI18N
        EMButton.setText("Exam Management");
        EMButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EMButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, 90));

        QMButton.setBackground(new java.awt.Color(255, 204, 0));
        QMButton.setFont(new java.awt.Font("Adventure", 1, 36)); // NOI18N
        QMButton.setForeground(new java.awt.Color(0, 0, 0));
        QMButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/question.png"))); // NOI18N
        QMButton.setText("Question Management");
        QMButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QMButtonActionPerformed(evt);
            }
        });
        getContentPane().add(QMButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 470, -1));

        CloseButton.setBackground(new java.awt.Color(255, 255, 255));
        CloseButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        CloseButton.setForeground(new java.awt.Color(0, 0, 0));
        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Logout.png"))); // NOI18N
        CloseButton.setText("Logout");
        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 40, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/TeacherHomepageBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(jf,"do u realy want to log out","select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new SignIn().setVisible(true);
        }
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void EMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ExamManagement().setVisible(true);
    }//GEN-LAST:event_EMButtonActionPerformed

    private void QMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QMButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new QuestionManagement().setVisible(true);
    }//GEN-LAST:event_QMButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton EMButton;
    private javax.swing.JButton QMButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
