/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lms;
import java.sql.*;
 import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author A M A
 */
public class updateQuestion extends javax.swing.JFrame {

    /**
     * Creates new form updateQuestion
     */
    public updateQuestion() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CloseButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        QuestionIdLabel = new javax.swing.JLabel();
        AnswerLabel = new javax.swing.JLabel();
        Opt4Label = new javax.swing.JLabel();
        Opt3Label = new javax.swing.JLabel();
        Opt2Label = new javax.swing.JLabel();
        Opt1Label = new javax.swing.JLabel();
        QuestionLabel = new javax.swing.JLabel();
        CNameText = new javax.swing.JTextField();
        QuestionText = new javax.swing.JTextField();
        Opt1Text = new javax.swing.JTextField();
        Opt2Text = new javax.swing.JTextField();
        Opt3Text = new javax.swing.JTextField();
        Opt4Text = new javax.swing.JTextField();
        AnswerText = new javax.swing.JTextField();
        QuestionIdText = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(150, 183));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        CNameLabel.setText("Course Name :");
        getContentPane().add(CNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Adventure", 1, 40)); // NOI18N
        jLabel2.setText("UPDATE QUESTION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 6, 369, -1));

        CloseButton.setBackground(new java.awt.Color(255, 255, 255));
        CloseButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CloseButton.setForeground(new java.awt.Color(255, 0, 51));
        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Close.png"))); // NOI18N
        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 1066, 10));

        QuestionIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        QuestionIdLabel.setText("Question ID :");
        getContentPane().add(QuestionIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        AnswerLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        AnswerLabel.setText("Answer   :");
        getContentPane().add(AnswerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        Opt4Label.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Opt4Label.setText("Option 4 :");
        getContentPane().add(Opt4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        Opt3Label.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Opt3Label.setText("Option 3 :");
        getContentPane().add(Opt3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        Opt2Label.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Opt2Label.setText("Option 2 :");
        getContentPane().add(Opt2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        Opt1Label.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Opt1Label.setText("Option 1 :");
        getContentPane().add(Opt1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        QuestionLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        QuestionLabel.setText("Question :");
        getContentPane().add(QuestionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        CNameText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(CNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 700, -1));

        QuestionText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(QuestionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 700, -1));

        Opt1Text.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(Opt1Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 702, -1));

        Opt2Text.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(Opt2Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 702, -1));

        Opt3Text.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(Opt3Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 702, -1));

        Opt4Text.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(Opt4Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 702, -1));

        AnswerText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(AnswerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 703, -1));

        QuestionIdText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(QuestionIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 280, -1));

        SearchButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/search.png"))); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/save.png"))); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        ClearButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/clear.png"))); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        String id = QuestionIdText.getText();
        String name  = QuestionText.getText();
        String opt1 = Opt1Text.getText();
        String opt2 = Opt2Text.getText();
        String opt3 = Opt3Text.getText();
        String opt4 = Opt4Text.getText();
        String answer = AnswerText.getText();
        String CourseName =  CNameText.getText();
        try
        {
           Connection con = MyConnection.createConnection();
           PreparedStatement pa = con.prepareStatement("update question set Qname=?,opt1=?,opt2=?,opt3=?,opt4=?,answer=?,CourseName=? where id=? ");           
           pa.setString(1, name);
           pa.setString(2, opt1);
           pa.setString(3, opt2 );
           pa.setString(4, opt3 );
           pa.setString(5, opt4 );
           pa.setString(6, answer); 
           pa.setString(7, CourseName);        
           pa.setString(8, id);

           pa.executeUpdate();
           JFrame jf = new JFrame();
           jf.setAlwaysOnTop(true);
           JOptionPane.showMessageDialog(jf , "successfully Updated");
           setVisible(false);
           new updateQuestion().setVisible(true);                    
        }
        catch (Exception e)
        {
            JFrame jf = new JFrame();           
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , e);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
         QuestionIdText.setEditable(true);
         QuestionIdText.setText("");
         QuestionText.setText("");
         Opt1Text.setText("");
         Opt2Text.setText("");
         Opt3Text.setText("");
         Opt4Text.setText("");
         AnswerText.setText("");
         CNameText.setText("");

    }//GEN-LAST:event_ClearButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        QuestionManagement.open=0;
         setVisible(false);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String id = QuestionIdText.getText();
         try
        {
           Connection con = MyConnection.createConnection();
           Statement st = con.createStatement();
           ResultSet rs =st.executeQuery(" select * from question where id ="+id);
           if(rs.next())
           {
              QuestionText.setText(rs.getString(2));
              Opt1Text.setText(rs.getString(3));
              Opt2Text.setText(rs.getString(4));
              Opt3Text.setText(rs.getString(5));
              Opt4Text.setText(rs.getString(6));
              AnswerText.setText(rs.getString(7));
              CNameText.setText(rs.getString(8));
              QuestionIdText.setEditable(false);
           }
           else
           {
            JFrame jf = new JFrame();            
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , "Question ID does not exist");
           }
        }
        catch (Exception e)
        {
            JFrame jf = new JFrame();            
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , e);
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnswerLabel;
    private javax.swing.JTextField AnswerText;
    private javax.swing.JLabel CNameLabel;
    private javax.swing.JTextField CNameText;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel Opt1Label;
    private javax.swing.JTextField Opt1Text;
    private javax.swing.JLabel Opt2Label;
    private javax.swing.JTextField Opt2Text;
    private javax.swing.JLabel Opt3Label;
    private javax.swing.JTextField Opt3Text;
    private javax.swing.JLabel Opt4Label;
    private javax.swing.JTextField Opt4Text;
    private javax.swing.JLabel QuestionIdLabel;
    private javax.swing.JTextField QuestionIdText;
    private javax.swing.JLabel QuestionLabel;
    private javax.swing.JTextField QuestionText;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
