package lms;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author A M A
 */
public class UpdateExam extends javax.swing.JFrame {

    /**
     * Creates new form UpdateExam
     */
    public UpdateExam() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CloseButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        CNameText = new javax.swing.JTextField();
        QID1Text = new javax.swing.JTextField();
        QID2Text = new javax.swing.JTextField();
        QID3Text = new javax.swing.JTextField();
        QID4Text = new javax.swing.JTextField();
        QID5Text = new javax.swing.JTextField();
        EIDText = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(150, 183));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Adventure", 1, 40)); // NOI18N
        jLabel2.setText("Update Exam ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 1066, 10));

        CloseButton.setBackground(new java.awt.Color(255, 255, 255));
        CloseButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CloseButton.setForeground(new java.awt.Color(255, 0, 51));
        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Close.png"))); // NOI18N
        CloseButton.setText("Close");
        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Exam ID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 105, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Course Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 159, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Question ID 1 :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 210, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Question ID 2 :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 261, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("Question ID 3 :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 312, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("Question ID 4 :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 363, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setText("Question ID 5 :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 414, -1, -1));

        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/save.png"))); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 477, -1, -1));

        ClearButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/clear.png"))); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 477, -1, -1));

        CNameText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(CNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 156, 700, -1));

        QID1Text.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(QID1Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 207, 700, -1));

        QID2Text.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(QID2Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 258, 700, -1));

        QID3Text.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(QID3Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 309, 700, -1));

        QID4Text.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(QID4Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 360, 700, -1));

        QID5Text.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(QID5Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 411, 700, -1));

        EIDText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(EIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 105, 266, -1));

        SearchButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/search.png"))); // NOI18N
        SearchButton.setText("Search");
        SearchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 105, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        ExamManagement.open=0;
        setVisible(false);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String id = EIDText.getText();
         try
        {
           Connection con = MyConnection.createConnection();
           Statement st = con.createStatement();
           ResultSet rs =st.executeQuery(" select * from quiz where id ="+id);
           if(rs.next())
           {             
             QID1Text.setText(rs.getString(2));
             QID2Text.setText(rs.getString(3));
             QID3Text.setText(rs.getString(4));
             QID4Text.setText(rs.getString(5));
             QID5Text.setText(rs.getString(6));
             CNameText.setText(rs.getString(7));        
             EIDText.setEditable(false);
           }
           else
           {
            JFrame jf = new JFrame();            
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , "Exam ID does not exist");
           }
        }
        catch (Exception e)
        {
            JFrame jf = new JFrame();            
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , e);
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        String id = EIDText.getText();
        String Qid1 =  QID1Text.getText();
        String Qid2 =  QID2Text.getText();
        String Qid3  = QID3Text.getText();
        String Qid4  =  QID4Text.getText();
        String Qid5  =  QID5Text.getText();
        String CourseName =  CNameText.getText();
        try
        {
           Connection con = MyConnection.createConnection();
           PreparedStatement pa = con.prepareStatement("update quiz set QID1=?,QID2=?,QID3=?,QID4=?,QID5=?,CourseName=? where id=? ");           
          
           pa.setString(1, Qid1);
           pa.setString(2, Qid2);
           pa.setString(3, Qid3);
           pa.setString(4, Qid4);
           pa.setString(5, Qid5);
           pa.setString(6, CourseName);     
            pa.setString(7, id);
           
           pa.executeUpdate();
           JFrame jf = new JFrame();
           jf.setAlwaysOnTop(true);
           JOptionPane.showMessageDialog(jf , "successfully Updated");
           setVisible(false);
           new UpdateExam().setVisible(true);                    
        }
        catch (Exception e)
        {
            JFrame jf = new JFrame();           
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf , e);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
         EIDText.setText("");
         QID1Text.setText("");
         QID2Text.setText("");
         QID3Text.setText("");
         QID4Text.setText("");
         QID5Text.setText("");
         CNameText.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CNameText;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JTextField EIDText;
    private javax.swing.JTextField QID1Text;
    private javax.swing.JTextField QID2Text;
    private javax.swing.JTextField QID3Text;
    private javax.swing.JTextField QID4Text;
    private javax.swing.JTextField QID5Text;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
